### ISSUE TITLE
improvements for indicator table

### ISSUE THREAD

**Issue by NejcHirci** [NejcHirci/WorldHappinessStudy#4]
Wanted additions:
- [x] #15
    - **Topic** (2 digits),
    - **General Subject** (3 digits),
    - **Specific Subject** (4 digits),
    - **Extensions** (2 digits for each, but max 3 extensions)
 - [x] Add relative/absolute field to table
 - [x] Improve sorting in index table so it works more like checkboxes and it sorts selected indexes always on top regardless of filter querry
 - [x] add attribute descriptions and url link to domain of table `data.domain.attributes[“EN.ATM.NOXE.AG.ZS’].attributes[“description”] = “Agricultural nitrous oxide emissions (% of total)”`

**Comment by BlazZupan** [comment]
Split "Index Selection" to two groups. Rename Index Selection to "Available Indicators" (in the table, rename Index->Indicator). The section table should be called "Selected Indicators". Implement drag and drop and add a button for moving selected indicators from one table to another. For example, see Select Columns.
